name: Build, Testing, Check coverage

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 build:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Install dependencies
    run: sudo apt-get update && sudo apt-get install -y gcovr lcov
  
  - name: Cloning gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest

  - name: Install cpp-coveralls
    run: pip install cpp-coveralls

  - name: Config banking
    run: cmake -H. -B${{github.workspace}}/build -DBUILD_TESTS=ON -DCOVERAGE=ON

  - name: Build banking
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check --enable-gcov

  - name: Measure coverage
  env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  run: coveralls -r build
  